spring.application.name=BootIocProj-15-BulkInjectionThroughConfigurationProperties-3

comp.sri.dept[0].deptId=101
comp.sri.dept[0].deptName=HR
comp.sri.dept[1].deptId=102
comp.sri.dept[1].deptName=IT
comp.sri.dept[2].deptId=103
comp.sri.dept[2].deptName=Finance

bank.acc.accNumber=123456789
bank.acc.holderName=sritam
bank.acc.balance=5000

lib.sri.books.a=java
lib.sri.books.b=effective java

student.details.list[0].id=101
student.details.list[0].name=sritam
student.details.list[0].marks=90

