spring.application.name=BootIocProj-09-LayeredApp-MiniProject-LabTask

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=sritam
spring.datasource.password=wolf
