spring.application.name=BootIocProj-15-BulkInjectionThroughConfigurationProperties

org.nit.name=naresh IT
org.nit.addr=hyd
org.nit.pincode=500036
org.nit.contact=99999999

#for array
org.nit.branches[0]=hyd
org.nit.branches[1]=delhi
org.nit.branches[2]=ny

#for List
org.nit.owners[0]=sritam
org.nit.owners[1]=subrat
org.nit.owners[2]=konda

#for Set
org.nit.phones[0]=222222
org.nit.phones[1]=333333
org.nit.phones[2]=1111111