spring.application.name=BootIocProj-21-BulkInjection

employee.id=101
employee.name=sritam
employee.salary=45000
employee.skills[]={java,spring boot,react}
employee.projects[0]=online electronic portal
employee.projects[1]=zomato clone
employee.tools[]={maven,github,eclipse}
employee.experience.j2ee=2              # j2ee=key,2=value
employee.addr.city=hyderabad
employee.addr.state=telengana
employee.addr.pincode=756001